### ISSUE TITLE
Error downloading dx toolkit 

### ISSUE THREAD

**Issue by kirbyjbirch** [stjude/sjcloud-data-transfer-app#38]
We had a internal user that had the following error: 
```
2018-02-02T15:41:37.897Z - error:  Error: Command failed: /usr/bin/env bash -c "[ -f /Users/vrudneva/.sjcloud/anaconda/envs/sjcloud/bin/dx ]"
 
    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

**Comment by claymcleod** [comment]
This is an expected error: when the app first starts up, it looks to see if `dx` is installed. In this case, this was the user's first time running the app, so I suspect they did not have `dx` installed. The app should recover gracefully from this, and I suspect that the causal error was later down in the logs. We believe we've fixed all of the installation bugs, so I'm going to close this for now.
